version: "3.8"

services:
  db:
    image: postgres:17.6
    container_name: debat_ai_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - debatai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: debat_ai_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    # --- AJOUT CRUCIAL ICI ---
    env_file:
      - .env
    # -------------------------
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    networks:
      - debatai-network

  frontend:
    build: ./frontend
    container_name: debat_ai_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - debatai-network

networks:
  debatai-network:
    driver: bridge

volumes:
  postgres_data:
